build_main:
  variables:
      GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.19.2-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"https://registry.supporterino.de\":{\"auth\":\"cm9ib3QkZ2l0bGFiOm1TVXNESWNJSThlVTVwV0I5SkNtVDJSeVRkeUs5WHVi==\"}}}" > /kaniko/.docker/config.json
    - export VERSION="v$(cat package.json | grep version | head -1 | awk -F':' '{ print $2 }' | sed 's/[\",]//g' | cut -c2-)"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "supporterino/dns-speed-tracker:latest"
      --destination "supporterino/dns-speed-tracker:${CI_COMMIT_SHORT_SHA}"
      --destination "supporterino/dns-speed-tracker:${VERSION}"
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"

build_branch:
  variables:
      GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.19.2-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"https://registry.supporterino.de\":{\"auth\":\"cm9ib3QkZ2l0bGFiOm1TVXNESWNJSThlVTVwV0I5SkNtVDJSeVRkeUs5WHVi==\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "supporterino/dns-speed-tracker:${CI_COMMIT_BRANCH}"
  rules:
    - if: $CI_COMMIT_BRANCH != "release" && $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"

build_merge:
  variables:
      GIT_SUBMODULE_STRATEGY: recursive
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.19.2-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"https://registry.supporterino.de\":{\"auth\":\"cm9ib3QkZ2l0bGFiOm1TVXNESWNJSThlVTVwV0I5SkNtVDJSeVRkeUs5WHVi==\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "supporterino/dns-speed-tracker:${CI_MERGE_REQUEST_IID}"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
